# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Run Myself (main)

on:
  push:
    branches:
      - main

jobs:
  self:
    name: Run Myself
    runs-on: ubuntu-latest
    steps:
    - name: Run Myself
      uses: ds-ukassel/yaml-ls-check@main
